version: '3'

services:

  nginx:
    image: namelessmc/nginx
    networks:
      default:
      namelessmc_proxy:
        ipv4_address: REPLACEME_IPADDR
    volumes: ['./web:/data:ro']
    depends_on: [php]
    restart: always

  php:
    image: namelessmc/php
    volumes: ['./web:/data']
    depends_on: [database]
    restart: always

  database:
    image: mariadb
    volumes: ['./db:/var/lib/mysql']
    environment:
      MYSQL_ROOT_PASSWORD: REPLACEME_DBPASSWORD
      MYSQL_DATABASE: nameless
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    network_mode: service:nginx
    volumes: [/sessions]
    environment:
      PMA_HOST: database
      PMA_ABSOLUTE_URI: REPLACEME_PHPMYADMINURI
      UPLOAD_LIMIT: 100M
    restart: always
    entrypoint: /bin/bash
    command: -c "sed -i 's/Listen 80/Listen 8080/g' /etc/apache2/ports.conf && /docker-entrypoint.sh apache2-foreground"

  webdav:
    image: webdav
    network_mode: service:nginx
    volumes: ['./web:/data/web']
    environment:
      USERNAME: REPLACEME_FILESUSER
      PASSWORD: REPLACEME_FILESPASSWORD
    restart: always

networks:
  namelessmc_proxy:
    external: true
